### ISSUE TITLE
possbily unhandled rejection error in console. 

### ISSUE THREAD

**Issue by nleibow** [den-wdi-2/rapid-prototype#1]
talked with Brian, he wasn't sure and hadn't previously seen the error. 

found this link to change what version of angular i was using but to no avail:
https://github.com/angular-ui/ui-router/issues/2889

found this link that points to a similar fix:
http://stackoverflow.com/questions/41063947/angular-1-6-0-possibly-unhandled-rejection-error

**Comment by ZebGirouard** [comment]
Fixed this issue, and found another error :)
